repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-yaml
      args: [--unsafe]
    - id: debug-statements
    - id: requirements-txt-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.1.0
    hooks:
    - id: pyupgrade
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.1.0
    hooks:
    - id: reorder-python-imports
      language_version: python3
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=120]
-   repo: https://github.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      args: [--max-line-length=120, "--extend-ignore=E203,E231"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    - id: mypy
      additional_dependencies: [marshmallow-dataclass==7.6.0]
